# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-17 10:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_editor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Editor',
        ),
    ]
